Properly (hopefully) quoting bash variables. Fixes #520

diff --git a/scripts/update_IDE b/scripts/update_IDE
--- a/scripts/update_IDE
+++ b/scripts/update_IDE
@@ -5,7 +5,7 @@
 # Bela directory before copying the files over
 
 [ -z "$BBB_ADDRESS" ] && BBB_ADDRESS="root@192.168.7.2"
-[ -z "$BBB_BELA_HOME" ] && BBB_BELA_HOME="~/Bela"
+[ -z "$BBB_BELA_HOME" ] && BBB_BELA_HOME="/root/Bela"
 
 ALWAYS_YES=0
 FULL=1
@@ -51,7 +51,7 @@ SCRIPTDIR=$(dirname "$0")
 
 printf "Warning: this script will DELETE any existing IDE files from your BeagleBone and install the IDE. Continue? (y/N) "
 
-if [ $ALWAYS_YES -eq 1 ];
+if [ "$ALWAYS_YES" -eq 1 ];
 then
   printf "y\n"
 else 
@@ -62,40 +62,40 @@ fi
 
 # Copy relevant files to BeagleBone Black
 printf "Copying new IDE files to BeagleBone..."
-[ -z $USE_RSYNC ] && { [ -z "`which rsync`" ] && USE_RSYNC=0 || USE_RSYNC=1; }
+[ -z "$USE_RSYNC" ] && { [ -z "`which rsync`" ] && USE_RSYNC=0 || USE_RSYNC=1; }
 
-if [ $USE_RSYNC -eq 1 ]
+if [ "$USE_RSYNC" -eq 1 ]
 then
   printf "using rsync..."
-  rsync -ac --no-t --delete-after $SCRIPTDIR/../IDE $BBB_ADDRESS:$BBB_BELA_HOME
+  rsync -ac --no-t --delete-after "$SCRIPTDIR"/../IDE "$BBB_ADDRESS":"$BBB_BELA_HOME"
 else
   #if rsync is not available, let's clean the folder first
-  ssh $BBB_ADDRESS "rm -rf $BBB_BELA_HOME/IDE ; mkdir -p $BBB_BELA_HOME/IDE" || { printf "\nError while removing the old files, is the board connected?\n"; exit 1; }
+  ssh "$BBB_ADDRESS" "rm -rf \"$BBB_BELA_HOME\"/IDE ; mkdir -p \"$BBB_BELA_HOME\"/IDE" || { printf "\nError while removing the old files, is the board connected?\n"; exit 1; }
   printf "using scp...might take a while ..."
-  scp -rq $SCRIPTDIR/../IDE $BBB_ADDRESS:$BBB_BELA_HOME
+  scp -rq "$SCRIPTDIR"/../IDE "$BBB_ADDRESS":"$BBB_BELA_HOME"
 fi
 [ $? -eq 0 ] &&\
 printf "done\n" || { printf "\nError while copying files: error $?\n"; exit 1; }
 
 # Make sure the projects folder exists and there is a project in it
-ssh $BBB_ADDRESS "cd $BBB_BELA_HOME/; mkdir -p $BBB_BELA_HOME/IDE/public/media; mkdir -p projects/; [ -d projects/basic ] || cp -r IDE/templates/basic projects/" &&\
+ssh "$BBB_ADDRESS" "cd \"$BBB_BELA_HOME\"/; mkdir -p \"$BBB_BELA_HOME\"/IDE/public/media; mkdir -p projects/; [ -d projects/basic ] || cp -r IDE/templates/C/ projects/basic/"
 
 # If there are any C/C++ files, rebuild node dependencies
-find $SCRIPTDIR/../IDE/node_modules | grep '\(\.cpp\|\.cc\|\.c\|\.hpp\|\.hh\|\.h\)$' >/dev/null 2>&1 &&\
+find "$SCRIPTDIR"/../IDE/node_modules | grep '\(\.cpp\|\.cc\|\.c\|\.hpp\|\.hh\|\.h\)$' >/dev/null 2>&1 &&\
 { 
 	printf "Rebuilding node dependencies..."
-	ssh $BBB_ADDRESS "cd $BBB_BELA_HOME/IDE/; npm rebuild &>/dev/null" &&\
+	ssh "$BBB_ADDRESS" "cd \"$BBB_BELA_HOME\"/IDE/; npm rebuild &>/dev/null" &&\
 	printf "done\n" || { printf "\nError while rebuilding dependencies.\n"; exit 1; }
 }
 
 echo "The IDE was correctly updated"
 
-[ $FULL -eq 1 ] && {
-	ssh $BBB_ADDRESS "make --no-print-directory -C \"$BBB_BELA_HOME\" idestart" ||\
+[ "$FULL" -eq 1 ] && {
+	ssh "$BBB_ADDRESS" "make --no-print-directory -C \"$BBB_BELA_HOME\" idestart" ||\
 	echo "Error while starting IDE" >&2
 }
 
-[ $ALWAYS_YES -eq 1 ] || [ $FULL -eq 0 ] && printf "\nSetup complete.\n\n" || {
+[ "$ALWAYS_YES" -eq 1 ] || [ "$FULL" -eq 0 ] && printf "\nSetup complete.\n\n" || {
   printf '\nIDE setup complete, press any key to continue . . .\n\n'
   read -n 1  
 }
